### PR TITLE
add imageData hint parameter

### LINKED ISSUE #4: Display image from buffer
Allow to display image from buffer by passing `image-data` hint. This is useful to display image from url or modified image where both are in memory.

### PR DESCRIPTION
**Pull request by daffamumtaz2361**
Fixes #4

### CODE REVIEW

**Comment by Hill-98** [comment]
I think it's better not to calculate channels and bits inside the library, since it might not be an RGB image.
Better to just convert JavaScript objects to (iiibiiay).

**Comment by daffamumtaz2361** [comment]
Channels has only 2 possible values, either 4 for transparent image, or 3 otherwise. The hasAlpha property should cover that.

I don't quite understand what you mean by bit here. If what you mean is bits_per_sample then it needs to be hardcoded to 8 as per the spec. If what you mean is rowstride, honestly I don't know much about it, I got that formula after my research. If there's other formula for rowstride, please do tell me

**Comment by daffamumtaz2361** [comment]
Oh I just realized something, the image data needs to be RGB as per the spec

> Formats
> The "image-data" and "icon_data" hints should be a DBus structure of signature (iiibiiay). The components of this structure are as follows:
>    width (i): Width of image in pixels
>    height (i): Height of image in pixels
>    rowstride (i): Distance in bytes between row starts
>    has_alpha (b): Whether the image has an alpha channel
>    bits_per_sample (i): Must always be 8
>    channels (i): If has_alpha is TRUE, must be 4, otherwise 3
>    data (ay): The image data, in **RGB byte order**

**Comment by daffamumtaz2361** [comment]
@Hill-98 Ping! Can this be merged and released soon? I'd like to use it in my project

**Comment by Hill-98** [comment]
No problem, I'll merge and release a new version tomorrow.

**Pull request merged**
